name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir imagen Docker
        run: |
          docker build -t miapp:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Etiquetar y subir imagen Docker
        run: |
          docker tag miapp:latest usuario/miapp:latest
          docker push usuario/miapp:latest

      - name: Desplegar en servidor
        run: |
          ssh usuario@servidor "docker pull usuario/miapp:latest && docker-compose up -d"
